controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controller Spawner Configurations
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint State Broadcaster Parameters
joint_state_broadcaster:
  ros__parameters:
    # If your robot hardware doesn't export all joints, you can add them here.
    # Otherwise, this can be left empty.
    extra_joints: [] 

# Arm Controller Parameters
arm_controller:
  ros__parameters:
    # List of joints that this controller will manage
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    # Interfaces to command the hardware
    command_interfaces:
      - position

    # Interfaces to read state from the hardware
    state_interfaces:
      - position
      - velocity

    # Allows the trajectory to end with non-zero velocity. 
    # Useful for dynamic movements.
    allow_nonzero_velocity_at_trajectory_end: true

    # PID gains for each joint. These are crucial for performance.
    gains:
      joint_1: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}
      joint_2: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}
      joint_3: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}
      joint_4: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}
      joint_5: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}
      joint_6: {p: 100.0, i: 10.0, d: 1.0, i_clamp: 10.0}