# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      joint_1: {p: 100.0, i: 10.0, d: 1.0}
      joint_2: {p: 100.0, i: 10.0, d: 1.0}
      joint_3: {p: 100.0, i: 10.0, d: 1.0}
      joint_4: {p: 100.0, i: 10.0, d: 1.0}
      joint_5: {p: 100.0, i: 10.0, d: 1.0}
      joint_6: {p: 100.0, i: 10.0, d: 1.0}